<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the audriga oof plugin                           |
 |                                                                       |
 +-----------------------------------------------------------------------+
*/

$labels['includeinvacationnotice'] = 'Strukturierte Daten an Urlaubsmitteilung anfügen';
$labels['includeinoutgoingmail'] = 'Strukturierte Daten an ausgehende Emails anhängen';
$labels['dayspriorinclude'] = 'Anzahl der Tage vor dem Urlaub, an denen bereits strukturierte Daten an ausgehende Emails angehängt werden';
$labels['days'] = 'Tage';
