<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the audriga oof plugin                           |
 |                                                                       |
 +-----------------------------------------------------------------------+
*/

$labels['includeinvacationnotice'] = 'Include Structured Data in Vacation Notice';
$labels['includeinoutgoingmail'] = 'Include Structured Data in Outgoing Email';
$labels['dayspriorinclude'] = 'Number of Days Prior To Vacation to Include Structured Data in Outgoing Email';
$labels['days'] = 'days';